base_url = "https://www.stanistan.com"
title = "stanistan"

compile_sass = true
highlight_code = true
highlight_theme = "inspired-github"
build_search_index = false
taxonomies = [
#    { name = "tags" },
]

[extra]
repo_content_path = "stanistan/stanistan.github.io/the-details/content"
show_tags = false # now tags taxonomy just yet
debug = false
