base_url = "https://stanistan.com"
title = "stanistan"

compile_sass = true
highlight_code = true
highlight_theme = "inspired-github"
build_search_index = false
taxonomies = [
#    { name = "tags" },
]

[extra]
show_tags = false # now tags taxonomy just yet
debug = true
